# automatically generated by the FlatBuffers compiler, do not modify

# namespace: chatty_fbs

class ActLayer(object):
    NONE = 0
    RELU = 1
    GELU = 2
    SWISH = 3
    SIGMOID = 4
    TANH = 5
    SOFTMAX = 6
