# automatically generated by the FlatBuffers compiler, do not modify

# namespace: chatty_fbs

class DType(object):
    NONE = 0
    INT8 = 1
    UINT8 = 2
    INT16 = 3
    UINT16 = 4
    INT32 = 5
    UINT32 = 6
    INT64 = 7
    UINT64 = 8
    FLOAT32 = 9
    FLOAT16 = 10
    FLOAT8 = 11
    BFLOAT16 = 12
    INT4 = 13
