# automatically generated by the FlatBuffers compiler, do not modify

# namespace: chatty_fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Norm(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Norm()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNorm(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Norm
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Norm
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Norm
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from chatty_fbs.Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Norm
    def Bias(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from chatty_fbs.Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Norm
    def Epsilon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Norm
    def ScaleX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from chatty_fbs.ScaleInfo import ScaleInfo
            obj = ScaleInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Norm
    def ScaleO(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from chatty_fbs.ScaleInfo import ScaleInfo
            obj = ScaleInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def NormStart(builder):
    builder.StartObject(6)

def Start(builder):
    NormStart(builder)

def NormAddType(builder, type):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(type), 0)

def AddType(builder, type):
    NormAddType(builder, type)

def NormAddWeight(builder, weight):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(weight), 0)

def AddWeight(builder, weight):
    NormAddWeight(builder, weight)

def NormAddBias(builder, bias):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(bias), 0)

def AddBias(builder, bias):
    NormAddBias(builder, bias)

def NormAddEpsilon(builder, epsilon):
    builder.PrependFloat32Slot(3, epsilon, 0.0)

def AddEpsilon(builder, epsilon):
    NormAddEpsilon(builder, epsilon)

def NormAddScaleX(builder, scaleX):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(scaleX), 0)

def AddScaleX(builder, scaleX):
    NormAddScaleX(builder, scaleX)

def NormAddScaleO(builder, scaleO):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(scaleO), 0)

def AddScaleO(builder, scaleO):
    NormAddScaleO(builder, scaleO)

def NormEnd(builder):
    return builder.EndObject()

def End(builder):
    return NormEnd(builder)

import chatty_fbs.ScaleInfo
import chatty_fbs.Tensor
try:
    from typing import Optional
except:
    pass

class NormT(object):

    # NormT
    def __init__(self):
        self.type = None  # type: str
        self.weight = None  # type: Optional[chatty_fbs.Tensor.TensorT]
        self.bias = None  # type: Optional[chatty_fbs.Tensor.TensorT]
        self.epsilon = 0.0  # type: float
        self.scaleX = None  # type: Optional[chatty_fbs.ScaleInfo.ScaleInfoT]
        self.scaleO = None  # type: Optional[chatty_fbs.ScaleInfo.ScaleInfoT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        norm = Norm()
        norm.Init(buf, pos)
        return cls.InitFromObj(norm)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, norm):
        x = NormT()
        x._UnPack(norm)
        return x

    # NormT
    def _UnPack(self, norm):
        if norm is None:
            return
        self.type = norm.Type()
        if norm.Weight() is not None:
            self.weight = chatty_fbs.Tensor.TensorT.InitFromObj(norm.Weight())
        if norm.Bias() is not None:
            self.bias = chatty_fbs.Tensor.TensorT.InitFromObj(norm.Bias())
        self.epsilon = norm.Epsilon()
        if norm.ScaleX() is not None:
            self.scaleX = chatty_fbs.ScaleInfo.ScaleInfoT.InitFromObj(norm.ScaleX())
        if norm.ScaleO() is not None:
            self.scaleO = chatty_fbs.ScaleInfo.ScaleInfoT.InitFromObj(norm.ScaleO())

    # NormT
    def Pack(self, builder):
        if self.type is not None:
            type = builder.CreateString(self.type)
        if self.weight is not None:
            weight = self.weight.Pack(builder)
        if self.bias is not None:
            bias = self.bias.Pack(builder)
        if self.scaleX is not None:
            scaleX = self.scaleX.Pack(builder)
        if self.scaleO is not None:
            scaleO = self.scaleO.Pack(builder)
        NormStart(builder)
        if self.type is not None:
            NormAddType(builder, type)
        if self.weight is not None:
            NormAddWeight(builder, weight)
        if self.bias is not None:
            NormAddBias(builder, bias)
        NormAddEpsilon(builder, self.epsilon)
        if self.scaleX is not None:
            NormAddScaleX(builder, scaleX)
        if self.scaleO is not None:
            NormAddScaleO(builder, scaleO)
        norm = NormEnd(builder)
        return norm
