# automatically generated by the FlatBuffers compiler, do not modify

# namespace: chatty_fbs

class ActLayer(object):
    NONE = 0
    RELU = 1
    GELU = 2
    SILU = 3
    SWISH = 4
    SIGMOID = 5
    TANH = 6
    SOFTMAX = 7
